memgraph:
  ingress:
    enabled: true
    className: nginx  # Change this to your desired ingress class
    hosts:
      - host: memgraph.example.com  # Change this to your desired host
        paths:
          - path:
            pathType: ImplementationSpecific

  autoscaling:
    enabled: true