opentelemetry-collector:
  image:
    repository: otel/opentelemetry-collector
    tag: 0.129.0
    pullPolicy: IfNotPresent
  command:
    name: otelcol
  mode: statefulset
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: otel-collector.example.com
        paths:
          - path: /
            pathType: Prefix
            port: 4318