n8n:
  n8n:
    encryption_key: test

  ingress:
    enabled: true
    hosts:
      - host: n8n.example.com
        paths:
          - path: /

  redis:
    enabled: true
  persistence:
    enabled: true