ingress-nginx:
  controller:
    replicaCount: 1

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1

    ingressClassResource:
      name: nginx
      enabled: true
      default: true

    ingressClass: nginx

    service:
      type: NodePort

    watchIngressWithoutClass: true
    allowSnippetAnnotations: true

    admissionWebhooks:
      enabled: true
      patch:
        enabled: true

    hostPort:
      enabled: true

    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

    serviceAccount:
      create: true
      name: ingress-nginx

    publicService:
      enabled: false
    extraArgs:
      publish-status-address: localhost

  # defaultBackend:
  #   enabled: true

  # rbac:
  #   create: true

  # admissionWebhooks:
  #   create: true
  #   patch:
  #     enabled: true
  #   serviceAccount:
  #     create: true
  #     name: ingress-nginx-admission