kube-prometheus-stack:
  crds:
    enabled: true
    createAPIService: true
  prometheusOperator:
    enabled: true
    createCustomResource: true
  prometheus:
    enabled: true
    prometheusSpec:
      retention: 30d
  grafana:
    enabled: true
    adminPassword: prom-operator
  alertmanager:
    enabled: true
