{{- range $name, $app := .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.spec.namespace }}
spec:
  project: {{ $.Values.spec.project }}
  source:
    repoURL: {{ $.Values.spec.repoURL }}
    targetRevision: {{ $.Values.spec.target }}
    path: {{ $.Values.spec.path }}/{{ $name }}
    helm:
      valuesFiles:
        {{- if $app.valuesFiles }}
        {{- range $app.valuesFiles }}
        - {{ . }}
        {{- end }}
        {{- else }}
        - values.yaml
        {{- end }}
  destination:
    server: {{ $.Values.spec.cluster }}
    namespace: {{ default $name $app.namespace }}
  syncPolicy:
    {{- if $app.syncPolicy }}
    {{- with $app.syncPolicy }}
    syncOptions:
      {{- if .syncOptions }}
      {{- range .syncOptions }}
      - {{ . }}
      {{- end }}
      {{- end }}
    {{- if .syncWave }}
    syncWave: {{ .syncWave }}
    {{- end }}
    {{- end }}
    {{- else }}
    syncOptions:
      {{- if $app.createNamespace }}
      - CreateNamespace=true
      {{- end }}
    {{- end }}
  {{- if $app.dependsOn }}
  dependsOn:
    {{- range $app.dependsOn }}
    - {{ . }}
    {{- end }}
  {{- end }}
---
{{- end }}