{{- $spec := .Values.spec -}}
{{- range $name, $app := .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: {{ $spec.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: {{ $name }}
spec:
  project: {{ $spec.project }}
  source:
    repoURL: {{ $spec.repoURL }}
    targetRevision: {{ $spec.target }}
    path: {{ $spec.path }}/{{ $name }}
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: {{ $spec.cluster }}
    namespace: {{ $name }}
  syncPolicy:
    syncOptions:
      {{- if $app.createNamespace }}
      - CreateNamespace=true
      {{- end }}
---
{{- end }}