appProjects:
  enabled: true
  projects:
    - name: project
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    - name: product
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      namespaceResourceWhitelist:
        - group: '*'
          kind: '*'

argo-cd:
  fullnameOverride: argocd
  server:
    resources:
      limits:
        memory: "512Mi"
      requests:
        memory: "512Mi"

  repoServer:
    resources:
      limits:
        memory: "512Mi"
      requests:
        memory: "512Mi"

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    pathType: Prefix
    hosts:
      - host: argocd.example.com
        paths:
          - /

  applicationset:
    enabled: false

  configs:
    cm:
      create: true
      exec.enabled: true
      admin.enabled: true
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories:
        app-of-apps:
          url: https://github.com/SleepySouls/App-of-Apps.git
          type: git
          name: argocd-app-of-apps
          username: SleepySouls
          project: project

