spec:
  project: project
  repoURL: https://github.com/SleepySouls/App-of-Apps.git
  cluster: https://kubernetes.default.svc
  path: values/tool-app
  namespace: argocd
  target: main

applications:
  argocd:
    createNamespace: true
  ingress-nginx:
    createNamespace: true
  metallb:
    createNamespace: true
    namespace: metallb-system
  harbor:
    createNamespace: true