spec:
  project: project
  repoURL: https://github.com/SleepySouls/App-of-Apps.git
  cluster: https://kubernetes.default.svc
  path: values/tool-app
  namespace: argocd
  target: main

applications:
  argocd:
    createNamespace: true
  ingress-nginx:
    createNamespace: true
  metallb:
    createNamespace: true
    namespace: metallb-system
  harbor:
    createNamespace: true
  cert-manager:
    createNamespace: true
  kube-prometheus-stack:
    createNamespace: true
    namespace: monitoring
    dependsOn:
      - cert-manager
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      syncWave: 1
  argo-rollouts:
    createNamespace: true
    dependsOn:
      - kube-prometheus-stack
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      syncWave: 2