spec:
  project: project
  repoURL: https://github.com/SleepySouls/App-of-Apps.git
  cluster: https://kubernetes.default.svc
  path: values/tool-app
  namespace: argocd
  target: main

applications:
  argocd:
    createNamespace: true
    namespace: argocd
  ingress-nginx:
    createNamespace: true
    namespace: ingress-nginx
  harbor:
    createNamespace: true
    namespace: harbor
  k8s-resources:
    createNamespace: true
    namespace: tool-app
  anythingllm:
    createNamespace: true
    namespace: anythingllm
  librechat:
    createNamespace: true
    namespace: librechat
  n8n:
    createNamespace: true
    namespace: n8n
  memgraph:
    createNamespace: true
    namespace: memgraph
  kube-prometheus-stack:
    createNamespace: true
    namespace: monitoring
  argo-rollouts:
    createNamespace: true
    namespace: argo-rollouts
  pgvector:
    createNamespace: true
    namespace: pgvector