vault-secrets-reloader:
  image:
    repository: ghcr.io/bank-vaults/vault-secrets-reloader
    tag: "0.4.0"
    pullPolicy: IfNotPresent

  collectorSyncPeriod: 30m
  reloaderRunPeriod: 1h

  serviceAccount:
    create: true

  service:
    type: ClusterIP
    externalPort: 443
    internalPort: 8443

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80