vault-secrets-webhook:
  replicaCount: 2
  certificate:
    useCertManager: true
    servingCertificate: null
    generate: false

  image:
    repository: ghcr.io/bank-vaults/vault-secrets-webhook
    tag: "1.22.1"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    externalPort: 443
    internalPort: 8443

  vaultEnv:
    repository: ghcr.io/bank-vaults/vault-env
    tag: "1.22.0"

  serviceAccount:
    create: true
  
  namespaceSelector:
    matchLabels:
      vault-injection: "enabled"
    