vault-operator:
  crds:
    install: true

  image:
    repository: ghcr.io/bank-vaults/vault-operator
    tag: v1.23.0
    pullPolicy: IfNotPresent

  bankVaults:
    image:
      repository: ghcr.io/bank-vaults/bank-vaults
      tag: v1.32.0

  watchNamespaces: vault
  syncPeriod: 1m

  serviceAccount:
    create: true

  service:
    type: ClusterIP