librechat:
  librechat-rag-api:
    enabled: true
    embeddingsProvider: openai

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: librechat.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific