anything-llm:
  ingress:
    enabled: false
    hosts:
      - host: anythingllm.example.com
        paths:
          - path: /
            pathType: Prefix

  persistence:
    enabled: true
    accessModes: ReadWriteOnce
    size: 5Gi
    volumes:
      - name: anythingllm-pvc
        mountPath: /app/server/storage