apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anything-llm-ingress
  namespace: anythingllm
spec:
  ingressClassName: nginx
  rules:
    - host: anythingllm.example.com
      http:
        paths:
          - backend:
              service:
                name: anything-llm
                port:
                  number: 3001
            path: /
            pathType: Prefix