apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: project
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: main
    path: values/argocd
  destination:
    server: {{ .Values.cluster | quote }}
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true