metrics-server:
  rbac:
    create: true
  addonResizer:
    enabled: true
  apiService:
    insecureSkipTLSVerify: false
  metrics: 
    enabled: true
  serviceMonitor:
    enabled: true
  tls:
    type: "helm"
    lookup: true
    certDurationDays: 365